/* const rentedPrice = 20000;
console.log(rentedPrice.toLocaleString("en-US")); // Outputs: "20,000"
 */
[
  {
    "make": "Toyota",
    "model": "Corolla",
    "year": 2020,
    "rentedPrice": 50,
    "availability": true,
    "image": "https://example.com/images/toyota-corolla.jpg",
    "description":
      "A reliable compact car, perfect for city drives and long trips.",
  },
  {
    "make": "Honda",
    "model": "Civic",
    "year": 2022,
    "rentedPrice": 60,
    "availability": false,
    "image": "https://example.com/images/honda-civic.jpg",
    "description": "A stylish and fuel-efficient sedan with modern features.",
  },
  {
    "make": "Ford",
    "model": "Mustang",
    "year": 2019,
    "rentedPrice": 120,
    "availability": true,
    "image": "https://example.com/images/ford-mustang.jpg",
    "description": "A powerful sports car for thrilling rides.",
  },
  {
    "make": "Chevrolet",
    "model": "Impala",
    "year": 2021,
    "rentedPrice": 80,
    "availability": true,
    "image": "https://example.com/images/chevrolet-impala.jpg",
    "description": "A spacious and comfortable full-size sedan.",
  },
  {
    "make": "Tesla",
    "model": "Model 3",
    "year": 2023,
    "rentedPrice": 150,
    "availability": false,
    "image": "https://example.com/images/tesla-model-3.jpg",
    "description": "A cutting-edge electric car with autopilot features.",
  },
  {
    "make": "BMW",
    "model": "X5",
    "year": 2022,
    "rentedPrice": 200,
    "availability": true,
    "image": "https://example.com/images/bmw-x5.jpg",
    "description": "A luxurious SUV with excellent performance and comfort.",
  },
  {
    "make": "Audi",
    "model": "A4",
    "year": 2021,
    "rentedPrice": 90,
    "availability": true,
    "image": "https://example.com/images/audi-a4.jpg",
    "description": "A premium sedan with a smooth ride and advanced technology.",
  },
  {
    "make": "Hyundai",
    "model": "Elantra",
    "year": 2020,
    "rentedPrice": 4500,
    "availability": true,
    "image": "https://example.com/images/hyundai-elantra.jpg",
    "description": "An affordable and reliable car for everyday use.",
  },
  {
    "make": "Nissan",
    "model": "Altima",
    "year": 2019,
    "rentedPrice": 55,
    "availability": false,
    "image": "https://example.com/images/nissan-altima.jpg",
    "description": "A sleek sedan with a comfortable interior."
  },
  {
    "make": "Mercedes-Benz",
    "model": "C-Class",
    "year": 2023,
    "rentedPrice": 180,
    "availability": true,
    "image": "https://example.com/images/mercedes-c-class.jpg",
    "description": "A high-end luxury car with superior style and performance."
  },
  {
    "make": "Jeep",
    model: "Wrangler",
    year: 2021,
    rentedPrice: 100,
    availability: true,
    image: "https://example.com/images/jeep-wrangler.jpg",
    description: "An off-road SUV built for adventure.",
  },
  {
    "make": "Kia",
    model: "Seltos",
    year: 2020,
    rentedPrice: 70,
    availability: true,
    image: "https://example.com/images/kia-seltos.jpg",
    description: "A versatile compact SUV with modern amenities.",
  },
  {
    "make": "Volkswagen",
    model: "Passat",
    year: 2019,
    rentedPrice: 65,
    availability: false,
    image: "https://example.com/images/volkswagen-passat.jpg",
    description: "A reliable mid-size sedan with a refined ride.",
  },
  {
    "make": "Subaru",
    model: "Outback",
    year: 2022,
    rentedPrice: 85,
    availability: true,
    image: "https://example.com/images/subaru-outback.jpg",
    description: "A rugged wagon ideal for both urban and outdoor adventures.",
  },
  {
    "make": "Mazda",
    model: "CX-5",
    year: 2021,
    rentedPrice: 75,
    availability: true,
    image: "https://example.com/images/mazda-cx-5.jpg",
    description: "A sporty SUV with exceptional handling and style.",
  },
];
